In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("hacker_news.csv")

In [3]:
df.head()

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48

In [4]:
df.tail()

,id,title,url,num_points,num_comments,author,created_at
20094,12379592,How Purism Avoids Intels Active Management Tec...,https://puri.sm/philosophy/how-purism-avoids-i...,10,6,AdmiralAsshat,8/29/2016 2:22
20095,10339284,YC Application Translated and Broken Down,https://medium.com/@zreitano/the-yc-applicatio...,4,1,zreitano,10/6/2015 14:57
20096,10824382,Microkernels are slow and Elvis didn't do no d...,http://blog.darknedgy.net/technology/2016/01/0...,169,132,vezzy-fnord,1/2/2016 0:49
20097,10739875,How Product Hunt really works,https://medium.com/@benjiwheeler/how-product-h...,695,222,brw12,12/15/2015 19:32
20098,11680777,RoboBrowser: Your friendly neighborhood web sc...,https://github.com/jmcarp/robobrowser,182,58,pmoriarty,5/12/2016 1:43

In [7]:
titles = df["title"]

In [10]:
num_titles_python = len([title for title in titles if "python" in title.lower()])

In [11]:
print(num_titles_python)

160

In [12]:
num_titles_javascript = len([title for title in titles if "javascript" in title.lower()])

In [13]:
print(num_titles_javascript)

170

In [14]:
df.describe()

                 id    num_points  num_comments
count  2.009900e+04  20099.000000  20099.000000
mean   1.131755e+07     50.296632     24.803025
std    6.964531e+05    107.110322     56.108639
min    1.017691e+07      1.000000      1.000000
25%    1.070172e+07      3.000000      1.000000
50%    1.128452e+07      9.000000      3.000000
75%    1.192613e+07     54.000000     21.000000
max    1.257898e+07   2553.000000   1733.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20099 entries, 0 to 20098
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20099 non-null  int64
 1   title         20099 non-null  object
 2   url           17659 non-null  object
 3   num_points    20099 non-null  int64
 4   num_comments  20099 non-null  int64
 5   author        20099 non-null  object
 6   created_at    20099 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.1+ MB